language: scala
dist: xenial

os:
  - linux

jdk:
  - openjdk8

scala:
  - 2.12.8

script:
  - sbt compile test

after_success:
  test "$TRAVIS_OS_NAME" = linux
  && travis_wait sbt codecov
  && bash <(curl -s https://codecov.io/bash)
